image: maven:latest

stages:
  - build
  - test
  - report

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

coverage:
  stage: report
  script:
    - mvn install -B
    - mvn site
    - cat target/site/index.html
  coverage: '/Total.*?ctr2.*?ctr2">([0-9]{1,3})%/'
  artifacts:
    name: test_coverage
    paths:
      - target/site/jacoco/

